.\" **************************************************************************
.\" Copyright (C) Samuel Henrique <samueloph@debian.org>, Sergio Durigan
.\" Junior <sergiodj@debian.org> and many contributors, see the AUTHORS
.\" file.
.\"
.\" Permission to use, copy, modify, and distribute this software for any purpose
.\" with or without fee is hereby granted, provided that the above copyright
.\" notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. IN
.\" NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
.\" DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
.\" OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
.\" OR OTHER DEALINGS IN THE SOFTWARE.
.\"
.\" Except as contained in this notice, the name of a copyright holder shall not be
.\" used in advertising or otherwise to promote the sale, use or other dealings in
.\" this Software without prior written authorization of the copyright holder.
.\"
.\" SPDX-License-Identifier: curl
.\" **************************************************************************
.TH wcurl "1" "2025.02.24" "wcurl" "User Commands"
.SH NAME
.B wcurl
- a simple wrapper around curl to easily download files.
.SH SYNOPSIS
.nf
\fBwcurl \fI<URL>\fP...\fR
\fBwcurl [\-\-curl\-options \fI<CURL_OPTIONS>\fP]... [\-\-dry\-run] [\-\-no\-decode\-filename] [\-o|\-O|\-\-output <PATH>] [\-\-] \fI<URL>\fP...\fR
\fBwcurl [\-\-curl\-options=\fI<CURL_OPTIONS>\fP]... [\-\-dry\-run] [\-\-no\-decode\-filename] [\-\-output=<PATH>] [\-\-] \fI<URL>\fP...\fR
\fBwcurl \-V|\-\-version\fR
\fBwcurl \-h|\-\-help\fR
.fi
.SH DESCRIPTION
\fBwcurl\fR is a simple curl wrapper which lets you use curl to download files
without having to remember any parameters.
.PP
Simply call \fBwcurl\fR with a list of URLs you want to download and \fBwcurl\fR will pick
sane defaults.
.PP
If you need anything more complex, you can provide any of curl's supported
parameters via the \fB\-\-curl\-options\fR option. Just beware that you likely
should be using curl directly if your use case is not covered.
.PP
.TP
By default, \fBwcurl\fR will:
.br
\[bu]  Percent-encode whitespaces in URLs;
.br
\[bu]  Download multiple URLs in parallel if the installed curl's version is >= 7.66.0;
.br
\[bu]  Follow redirects;
.br
\[bu]  Automatically choose a filename as output;
.br
\[bu]  Avoid overwriting files if the installed curl's version is >= 7.83.0 (--no-clobber);
.br
\[bu]  Perform retries;
.br
\[bu]  Set the downloaded file timestamp to the value provided by the server, if available;
.br
\[bu]  Default to the protocol used as https if the URL doesn't contain any;
.br
\[bu]  Disable \fBcurl\fR's URL globbing parser so \fB{}\fR and \fB[]\fR characters in URLs are not treated specially;
.br
\[bu]  Percent-decode the resulting filename;
.br
\[bu]  Use "index.html" as default filename if there's none in the URL.
.SH OPTIONS
.TP
\fB\-\-curl\-options, \-\-curl\-options=\fI<CURL_OPTIONS>\fR...\fR
Specify extra options to be passed when invoking curl. May be specified more than once.
.TP
\fB\-o, \-O, \-\-output, \-\-output=\fI<PATH>\fR...\fR
Use the provided output path instead of getting it from the URL. If multiple
URLs are provided, all files will have the same name with a number appended to
the end (curl >= 7.83.0). If this option is provided multiple times, only the
last value is considered.
.TP
\fB\-\-dry\-run\fR
Don't actually execute curl, just print what would be invoked.
.TP
\fB\-V, \-\-version\fR
Print version information.
.TP
\fB\-h, \-\-help\fR
Print help message.
.SH CURL_OPTIONS
Any option supported by curl can be set here.
This is not used by \fBwcurl\fR; it's instead forwarded to the curl invocation.
.SH URL
Anything which is not a parameter will be considered an URL.
\fBwcurl\fR will percent-encode whitespaces and pass that to curl, which will perform the
parsing of the URL.
.SH EXAMPLES
Download a single file:
.br
\fBwcurl example.com/filename.txt\fR
.PP
Download two files in parallel:
.br
\fBwcurl example.com/filename1.txt example.com/filename2.txt\fR
.PP
Download a file passing the \fI\-\-progress\-bar\fR and \fI\-\-http2\fR flags to curl:
.br
\fBwcurl \-\-curl\-options="\-\-progress\-bar \-\-http2" example.com/filename.txt\fR
.PP
Resume from an interrupted download (if more options are used, this needs to be the last one in the list):
.br
\fBwcurl \-\-curl\-options="\-\-continue-at \-" example.com/filename.txt\fR
.SH AUTHORS
Samuel Henrique <samueloph@debian.org>
.br
Sergio Durigan Junior <sergiodj@debian.org>
.br
and many contributors, see the AUTHORS file.
.SH REPORTING BUGS
If you experience any problems with \fBwcurl\fR that you do not experience with curl,
submit an issue on Github:
.br
https://github.com/curl/wcurl
.SH COPYRIGHT
\fBwcurl\fR is licensed under the curl license
.SH SEE ALSO
.BR curl (1)
